### ISSUE TITLE
Admin Console displays failure to sign in to Azure error

### ISSUE THREAD

**Issue by MSFTJerryAb** [MicrosoftDocs/SCCMdocs#1608]
**Under this:** https://docs.microsoft.com/en-us/sccm/core/plan-design/security/enable-tls-1-2
~~~~~~~~~~~~~~~~~~~~~~~~~~
Admin Console displays failure to sign in to Azure

If the Azure Services onboarding dialog box immediately fails after you click “Sign in” when you try to create Azure AD applications, verify that .NET Framework is updated and that strong cryptography is enabled. A restart is required for these changes to take effect.
~~~~~~~~~~~~~~~~~~~~~~~~~~
**Can we add this, for better discoverability of the related issue:**

The SMSAdminui.log may contain an error similar to the following:

Microsoft.ConfigurationManager.CloudBase.AAD.AADAuthenticationException
Service returned error. Check InnerException for more details
   at Microsoft.ConfigurationManager.CloudBase.AAD.AADAuthenticationContext.GetAADAuthResultObject(String clientID, Uri redirectUri, String authority, PromptBehavior promptBehavior)
   at Microsoft.ConfigurationManagement.AdminConsole.CloudServicesManagement.AAD.AADDataHandler.GetAuthResultObject()
   at Microsoft.ConfigurationManagement.AdminConsole.CloudServicesManagement.AAD.AADDataHandler..ctor(ConnectionManagerBase connectionManager, AzureEnvironment azureEnvironment, IAzureEnvironmentInformation environmentInformation, CloudServiceAssociatedAADData selectedCloudApp, String appName, String identifierUrl, String homepageUrl, String replyUrl, SecretKeyExpiryPeriod expiryPeriod)
   at Microsoft.ConfigurationManagement.AdminConsole.CloudServicesManagement.Dialogs.AADAppDetailsDialog.SignIn_OnClick(Object sender, EventArgs e)
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException
Service returned error. Check InnerException for more details
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.ConfigurationManager.CloudBase.AAD.AADAuthenticationContext.GetAADAuthResultObject(String clientID, Uri redirectUri, String authority, PromptBehavior promptBehavior)
System.Net.WebException
The underlying connection was closed: An unexpected error occurred on a receive.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()

In the System EventLog, SChannel EventID 36874 may be logged with the following description: An TLS 1.2 connection request was received from a remote client application, but none of the cipher suites supported by the client application are supported by the server. The TLS connection request has failed.

**Comment by aczechowski** [comment]
Thanks @MSFTJerryAb for the suggestion! I just added it, which is why the issue is now closed. But note it won't see the light of day until Monday's daily publishing (3 June) around 11am Pacific time.
